cache: bundler

language:
  - ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5

install:
  - "travis_retry bin/setup"

script:
  - "bundle exec appraisal rake"

branches:
  only:
    - master
    - 2.0

sudo: false
