rvm:
  - ree-1.8.7
  - 1.8.7
  - 1.9.2
  - 1.9.3
before_install:
  - gem update --system
script: 'bundle exec rake appraisal spec cucumber'
gemfile:
  - gemfiles/3.0.9.gemfile
  - gemfiles/3.1.0.gemfile
branches:
  only:
    - master
